#[programs.localnet]
disks_staking_program = "ABxTX1onDRNRfQHadz2mE49e8pN84hrSfSx6cggaxiJk"

[programs.devnet]
disks_staking_program = "ABxTX1onDRNRfQHadz2mE49e8pN84hrSfSx6cggaxiJk"

#[programs.mainnet]
#disks_staking_program = "ABxTX1onDRNRfQHadz2mE49e8pN84hrSfSx6cggaxiJk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "localnet"
cluster = "devnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
