#[programs.localnet]
disks_staking_program = "2xW3UNDFF7Pdz72Zc855DFQyM4uS7zrtFzYVvjZmaY91"

[programs.devnet]
disks_staking_program = "2xW3UNDFF7Pdz72Zc855DFQyM4uS7zrtFzYVvjZmaY91"

#[programs.mainnet]
#disks_staking_program = "2xW3UNDFF7Pdz72Zc855DFQyM4uS7zrtFzYVvjZmaY91"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
#cluster = "devnet"
wallet = "/Users/sven/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
